<?xml version="1.0" encoding="utf-8"?><Database Name="bdBarberia" Class="ConexionDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-RCI24OL\SQLEXPRESS;Initial Catalog=bdBarberia;Integrated Security=True;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="AccesoDatos.Properties.Settings" SettingsPropertyName="bdBarberiaConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.SP_ACTIVAR_CUENTA" Method="SP_ACTIVAR_CUENTA">
    <Parameter Name="CORREO_ELECTRONICO" Parameter="cORREO_ELECTRONICO" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="NUMERORVERIFICACION" Parameter="nUMERORVERIFICACION" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="FECHA_ACTUAL" Parameter="fECHA_ACTUAL" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Parameter Name="FILASACTUALIZADAS" Parameter="fILASACTUALIZADAS" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ACTUALIZAR_ADMIN" Method="SP_ACTUALIZAR_ADMIN">
    <Parameter Name="ID_USUARIO" Parameter="iD_USUARIO" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="NOMBRE" Parameter="nOMBRE" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="APELLIDO" Parameter="aPELLIDO" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="CORREO_ELECTRONICO" Parameter="cORREO_ELECTRONICO" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="TELEFONO" Parameter="tELEFONO" Type="System.String" DbType="NVarChar(9)" />
    <Parameter Name="PASSWORD" Parameter="pASSWORD" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="SALT" Parameter="sALT" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ACTUALIZAR_BARBERO" Method="SP_ACTUALIZAR_BARBERO">
    <Parameter Name="ID_USUARIO" Parameter="iD_USUARIO" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="NOMBRE" Parameter="nOMBRE" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="APELLIDO" Parameter="aPELLIDO" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="CORREO_ELECTRONICO" Parameter="cORREO_ELECTRONICO" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="TELEFONO" Parameter="tELEFONO" Type="System.String" DbType="NVarChar(9)" />
    <Parameter Name="PASSWORD" Parameter="pASSWORD" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="SALT" Parameter="sALT" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ACTUALIZAR_CITA" Method="SP_ACTUALIZAR_CITA">
    <Parameter Name="ID_CITA" Parameter="iD_CITA" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="ID_BARBERO" Parameter="iD_BARBERO" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="ID_USUARIO" Parameter="iD_USUARIO" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="ID_SERVICIO" Parameter="iD_SERVICIO" Type="System.Int32" DbType="Int" />
    <Parameter Name="FECHA_HORA" Parameter="fECHA_HORA" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ESTADO" Parameter="eSTADO" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ACTUALIZAR_PRODUCTO" Method="SP_ACTUALIZAR_PRODUCTO">
    <Parameter Name="ID_PRODUCTO" Parameter="iD_PRODUCTO" Type="System.Int32" DbType="Int" />
    <Parameter Name="NOMBRE" Parameter="nOMBRE" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DESCRIPCION" Parameter="dESCRIPCION" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="PRECIO" Parameter="pRECIO" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="STOCK" Parameter="sTOCK" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ACTUALIZAR_SERVICIO" Method="SP_ACTUALIZAR_SERVICIO">
    <Parameter Name="ID_SERVICIO" Parameter="iD_SERVICIO" Type="System.Int32" DbType="Int" />
    <Parameter Name="NOMBRE" Parameter="nOMBRE" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DESCRIPCION" Parameter="dESCRIPCION" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="DURACION_MINUTOS" Parameter="dURACION_MINUTOS" Type="System.Int32" DbType="Int" />
    <Parameter Name="PRECIO" Parameter="pRECIO" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ACTUALIZAR_USUARIO" Method="SP_ACTUALIZAR_USUARIO">
    <Parameter Name="ID_USUARIO" Parameter="iD_USUARIO" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="NOMBRE" Parameter="nOMBRE" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="APELLIDO" Parameter="aPELLIDO" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="CORREO_ELECTRONICO" Parameter="cORREO_ELECTRONICO" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="TELEFONO" Parameter="tELEFONO" Type="System.String" DbType="NVarChar(9)" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_CAMBIAR_CONTRASEÑA" Method="SP_CAMBIAR_CONTRASEÑA">
    <Parameter Name="CORREO_ELECTRONICO" Parameter="cORREO_ELECTRONICO" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="NUMERORVERIFICACION" Parameter="nUMERORVERIFICACION" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="NUEVO_PASSWORD" Parameter="nUEVO_PASSWORD" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="NUEVO_SALT" Parameter="nUEVO_SALT" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="FECHA_ACTUAL" Parameter="fECHA_ACTUAL" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_CERRAR_SESION" Method="SP_CERRAR_SESION">
    <Parameter Name="SESION" Parameter="sESION" Type="System.String" DbType="NVarChar(MAX)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_CODIGO_CAMBIO_CONTRA" Method="SP_CODIGO_CAMBIO_CONTRA">
    <Parameter Name="CORREO_ELECTRONICO" Parameter="cORREO_ELECTRONICO" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="NUMERORVERIFICACION" Parameter="nUMERORVERIFICACION" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="FECHA_ACTUAL" Parameter="fECHA_ACTUAL" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_CONFIRMAR_PAGO" Method="SP_CONFIRMAR_PAGO">
    <Parameter Name="ID_FACTURA" Parameter="iD_FACTURA" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int64" DbType="BigInt" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ELIMINAR_ADMIN" Method="SP_ELIMINAR_ADMIN">
    <Parameter Name="ID_USUARIO" Parameter="iD_USUARIO" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ELIMINAR_CITA" Method="SP_ELIMINAR_CITA">
    <Parameter Name="ID_CITA" Parameter="iD_CITA" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="ID_USUARIO" Parameter="iD_USUARIO" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="FECHA_HORA_ACTUAL" Parameter="fECHA_HORA_ACTUAL" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ELIMINAR_PRODUCTO" Method="SP_ELIMINAR_PRODUCTO">
    <Parameter Name="ID_PRODUCTO" Parameter="iD_PRODUCTO" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ELIMINAR_SERVICIO" Method="SP_ELIMINAR_SERVICIO">
    <Parameter Name="ID_SERVICIO" Parameter="iD_SERVICIO" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_INICIO_SESION" Method="SP_INICIO_SESION">
    <Parameter Name="SESION" Parameter="sESION" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="USUARIO" Parameter="uSUARIO" Type="System.Int32" DbType="Int" />
    <Parameter Name="ORIGEN" Parameter="oRIGEN" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_INSERTAR_ADMIN" Method="SP_INSERTAR_ADMIN">
    <Parameter Name="NOMBRE" Parameter="nOMBRE" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="APELLIDO" Parameter="aPELLIDO" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="CORREO_ELECTRONICO" Parameter="cORREO_ELECTRONICO" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="TELEFONO" Parameter="tELEFONO" Type="System.String" DbType="NVarChar(9)" />
    <Parameter Name="PASSWORD" Parameter="pASSWORD" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="SALT" Parameter="sALT" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="NUMERORVERIFICACION" Parameter="nUMERORVERIFICACION" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="FECHA_ACTUAL" Parameter="fECHA_ACTUAL" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_INSERTAR_BARBERO" Method="SP_INSERTAR_BARBERO">
    <Parameter Name="NOMBRE" Parameter="nOMBRE" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="APELLIDO" Parameter="aPELLIDO" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="CORREO_ELECTRONICO" Parameter="cORREO_ELECTRONICO" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="TELEFONO" Parameter="tELEFONO" Type="System.String" DbType="NVarChar(9)" />
    <Parameter Name="PASSWORD" Parameter="pASSWORD" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="SALT" Parameter="sALT" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="NUMERORVERIFICACION" Parameter="nUMERORVERIFICACION" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="FECHA_ACTUAL" Parameter="fECHA_ACTUAL" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_INSERTAR_CITA" Method="SP_INSERTAR_CITA">
    <Parameter Name="ID_USUARIO" Parameter="iD_USUARIO" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="ID_BARBERO" Parameter="iD_BARBERO" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="ID_SERVICIO" Parameter="iD_SERVICIO" Type="System.Int32" DbType="Int" />
    <Parameter Name="FECHA_HORA" Parameter="fECHA_HORA" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <ElementType Name="SP_INSERTAR_CITAResult">
      <Column Name="Id_Cita" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_Hora" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Id_Servicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Servicio_Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Servicio_Duracion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Servicio_Precio" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
      <Column Name="Id_Barbero" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Barbero_Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Id_Usuario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Apellido" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Correo" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Telefono" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_INSERTAR_PRODUCTO" Method="SP_INSERTAR_PRODUCTO">
    <Parameter Name="NOMBRE" Parameter="nOMBRE" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DESCRIPCION" Parameter="dESCRIPCION" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="PRECIO" Parameter="pRECIO" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="STOCK" Parameter="sTOCK" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_INSERTAR_SERVICIO" Method="SP_INSERTAR_SERVICIO">
    <Parameter Name="NOMBRE" Parameter="nOMBRE" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DESCRIPCION" Parameter="dESCRIPCION" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="DURACION_MINUTOS" Parameter="dURACION_MINUTOS" Type="System.Int32" DbType="Int" />
    <Parameter Name="PRECIO" Parameter="pRECIO" Type="System.Decimal" DbType="Decimal(8,2)" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_INSERTAR_USUARIO" Method="SP_INSERTAR_USUARIO">
    <Parameter Name="NOMBRE" Parameter="nOMBRE" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="APELLIDO" Parameter="aPELLIDO" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="CORREO_ELECTRONICO" Parameter="cORREO_ELECTRONICO" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="TELEFONO" Parameter="tELEFONO" Type="System.String" DbType="NVarChar(9)" />
    <Parameter Name="PASSWORD" Parameter="pASSWORD" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="SALT" Parameter="sALT" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="NUMERORVERIFICACION" Parameter="nUMERORVERIFICACION" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="FECHA_ACTUAL" Parameter="fECHA_ACTUAL" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_LOGIN" Method="SP_LOGIN">
    <Parameter Name="CORREO_ELECTRONICO" Parameter="cORREO_ELECTRONICO" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="ID_USUARIO" Parameter="iD_USUARIO" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="HASH_PASSWORD" Parameter="hASH_PASSWORD" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Parameter Name="SALT" Parameter="sALT" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <ElementType Name="SP_LOGINResult">
      <Column Name="Id_Usuario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Id_Rol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Correo_Electronico" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_OBTENER_CITAS_BARBERO" Method="SP_OBTENER_CITAS_BARBERO">
    <Parameter Name="ID_BARBERO" Parameter="iD_BARBERO" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="SP_OBTENER_CITAS_BARBEROResult">
      <Column Name="Id_Cita" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_Hora" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Id_Usuario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Apellido" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Correo" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Telefono" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="Id_Barbero" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Barbero_Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Id_Servicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Servicio_Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Servicio_Duracion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Servicio_Precio" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_OBTENER_CITAS_POR_DIA" Method="SP_OBTENER_CITAS_POR_DIA">
    <Parameter Name="FECHA" Parameter="fECHA" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="SP_OBTENER_CITAS_POR_DIAResult">
      <Column Name="Id_Cita" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_Hora" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Id_Usuario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Apellido" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Correo" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Telefono" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="Id_Barbero" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Barbero_Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Id_Servicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Servicio_Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Servicio_Duracion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Servicio_Precio" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_OBTENER_CITAS_POR_DIA_BARBERO" Method="SP_OBTENER_CITAS_POR_DIA_BARBERO">
    <Parameter Name="ID_BARBERO" Parameter="iD_BARBERO" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="FECHA" Parameter="fECHA" Type="System.DateTime" DbType="Date" />
    <ElementType Name="SP_OBTENER_CITAS_POR_DIA_BARBEROResult">
      <Column Name="Id_Cita" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_Hora" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Id_Usuario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Apellido" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Correo" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Telefono" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="Id_Barbero" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Barbero_Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Id_Servicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Servicio_Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Servicio_Duracion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Servicio_Precio" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_OBTENER_CITAS_USUARIO" Method="SP_OBTENER_CITAS_USUARIO">
    <Parameter Name="ID_USUARIO" Parameter="iD_USUARIO" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="SP_OBTENER_CITAS_USUARIOResult">
      <Column Name="Id_Cita" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_Hora" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Id_Servicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Servicio_Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Servicio_Duracion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Servicio_Precio" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
      <Column Name="Id_Barbero" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Barbero_Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Id_Usuario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Apellido" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Correo" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Telefono" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_OBTENER_LISTAADMIN" Method="SP_OBTENER_LISTAADMIN">
    <ElementType Name="SP_OBTENER_LISTAADMINResult">
      <Column Name="Id_Usuario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Correo_Electronico" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="Id_Rol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_OBTENER_LISTABARBEROS" Method="SP_OBTENER_LISTABARBEROS">
    <ElementType Name="SP_OBTENER_LISTABARBEROSResult">
      <Column Name="Id_Usuario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Correo_Electronico" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="Id_Rol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_OBTENER_LISTAPRODUCTOS" Method="SP_OBTENER_LISTAPRODUCTOS">
    <ElementType Name="SP_OBTENER_LISTAPRODUCTOSResult">
      <Column Name="Id_Producto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
      <Column Name="Stock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_OBTENER_LISTASERVICIOS" Method="SP_OBTENER_LISTASERVICIOS">
    <ElementType Name="SP_OBTENER_LISTASERVICIOSResult">
      <Column Name="Id_Servicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Duracion_Minutos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_OBTENER_LISTAUSUARIOS" Method="SP_OBTENER_LISTAUSUARIOS">
    <ElementType Name="SP_OBTENER_LISTAUSUARIOSResult">
      <Column Name="Id_Usuario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Correo_Electronico" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="Id_Rol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_OBTENER_USUARIO" Method="SP_OBTENER_USUARIO">
    <Parameter Name="ID_USUARIO" Parameter="iD_USUARIO" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="SP_OBTENER_USUARIOResult">
      <Column Name="Id_Usuario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Correo_Electronico" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="Id_Rol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_SOLICITAR_NUEVO_CODIGO" Method="SP_SOLICITAR_NUEVO_CODIGO">
    <Parameter Name="CORREO_ELECTRONICO" Parameter="cORREO_ELECTRONICO" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="NUMERORVERIFICACION" Parameter="nUMERORVERIFICACION" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="FECHA_ACTUAL" Parameter="fECHA_ACTUAL" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_ELIMINAR_USUARIO" Method="SP_ELIMINAR_USUARIO">
    <Parameter Name="ID_USUARIO" Parameter="iD_USUARIO" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_OBTENER_TODAS_CITAS" Method="SP_OBTENER_TODAS_CITAS">
    <ElementType Name="SP_OBTENER_TODAS_CITASResult">
      <Column Name="Id_Cita" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_Hora" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Id_Usuario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Apellido" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Correo" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Telefono" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="Id_Barbero" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Barbero_Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Id_Servicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Servicio_Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Servicio_Duracion" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Servicio_Precio" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_CONFIRMAR_CITA_TERMINADA" Method="SP_CONFIRMAR_CITA_TERMINADA">
    <Parameter Name="ID_CITA" Parameter="iD_CITA" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="ID_USUARIO" Parameter="iD_USUARIO" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_MARCAR_CITA_NO_ASISTIO" Method="SP_MARCAR_CITA_NO_ASISTIO">
    <Parameter Name="ID_CITA" Parameter="iD_CITA" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="ID_USUARIO" Parameter="iD_USUARIO" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_INSERTAR_FACTURA_PRODUCTO" Method="SP_INSERTAR_FACTURA_PRODUCTO">
    <Parameter Name="ID_USUARIO" Parameter="iD_USUARIO" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="FECHA" Parameter="fECHA" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ESTADO" Parameter="eSTADO" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="PRODUCTOS_JSON" Parameter="pRODUCTOS_JSON" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <ElementType Name="SP_INSERTAR_FACTURA_PRODUCTOResult">
      <Column Name="Id_Factura" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_Factura" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Subtotal" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="Estado_Factura" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Id_Producto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre_Producto" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Precio_Unitario" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Total_Producto" Type="System.Decimal" DbType="Decimal(21,2)" CanBeNull="true" />
      <Column Name="Nuevo_Stock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre_Cliente" Type="System.String" DbType="NVarChar(101) NOT NULL" CanBeNull="false" />
      <Column Name="Correo_Electronico" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_LISTAR_FACTURAS_USUARIO_PRODUCTOS" Method="SP_LISTAR_FACTURAS_USUARIO_PRODUCTOS">
    <Parameter Name="Id_Usuario" Parameter="id_Usuario" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="SP_LISTAR_FACTURAS_USUARIO_PRODUCTOSResult">
      <Column Name="Id_Factura" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_Factura" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Subtotal" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="Estado_Factura" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Id_Producto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nombre_Producto" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Precio_Unitario" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Total_Producto" Type="System.Decimal" DbType="Decimal(21,2)" CanBeNull="true" />
      <Column Name="Id_Usuario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Apellido" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Correo" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Telefono" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_LISTAR_FACTURAS_USUARIO_CITAS" Method="SP_LISTAR_FACTURAS_USUARIO_CITAS">
    <Parameter Name="IdUsuario" Parameter="idUsuario" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="SP_LISTAR_FACTURAS_USUARIO_CITASResult">
      <Column Name="Id_Factura" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Subtotal" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Id_Cita" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Fecha_Cita" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Servicio" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Descripcion" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Duracion_Minutos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Precio_Servicio" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
      <Column Name="Id_Usuario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Apellido" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Correo" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Usuario_Telefono" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_INSERTAR_FACTURA_CITA" Method="SP_INSERTAR_FACTURA_CITA">
    <Parameter Name="ID_USUARIO" Parameter="iD_USUARIO" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="ID_CITA" Parameter="iD_CITA" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="FECHA" Parameter="fECHA" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ESTADO" Parameter="eSTADO" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <ElementType Name="SP_INSERTAR_FACTURA_CITAResult">
      <Column Name="Id_Factura" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Id_Usuario" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="NombreUsuario" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CorreoUsuario" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Subtotal" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Id_Cita" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FechaCita" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Id_Servicio" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NombreServicio" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PrecioServicio" Type="System.Decimal" DbType="Decimal(8,2) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ELIMINAR_BARBERO" Method="SP_ELIMINAR_BARBERO">
    <Parameter Name="ID_USUARIO" Parameter="iD_USUARIO" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="IDRETURN" Parameter="iDRETURN" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORID" Parameter="eRRORID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Parameter Name="ERRORDESCRIPCION" Parameter="eRRORDESCRIPCION" Type="System.String" DbType="NVarChar(MAX)" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>